name: Demo
run-name: Primera GitHub Action de ${{ github.actor }} âœ¨
on: [push]
jobs:
  Mi-primera-GitHub-Action:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ‰ Evento de tipo ${{ github.event_name }}."
      - run: echo "ğŸ§ Job corriendo en ${{ runner.os }} en GitHub!"
      - run: echo "ğŸ” Branch ${{ github.ref }} del repo ${{ github.repository }}."
      - name: Clonando desde el repositorio 
        uses: actions/checkout@v4
      - run: echo "ğŸ’¡ El repo ${{ github.repository }} se clona en el runner."
      - run: echo "ğŸ–¥ï¸ Workflow listo para ejecutar el runner."
      - name: Listando los contenidos del repositorio
        run: |
          ls ${{ github.workspace }}
      - run: echo "ğŸ El status de este job es ${{ job.status }}."